# Generated by Django 5.0.1 on 2025-10-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('degree', models.CharField(blank=True, max_length=100, null=True)),
                ('college', models.CharField(blank=True, max_length=200, null=True)),
                ('graduation_year', models.CharField(blank=True, max_length=10, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('projects_title', models.CharField(blank=True, max_length=200, null=True)),
                ('project_desc', models.TextField(blank=True, null=True)),
                ('project_link', models.URLField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
